spring:
  application:
    name: bediende-service
  jackson:
    serialization:
      write_dates_as_timestamps: false

server:
  port: 8082

logging:
  level:
    root: WARN
    company.tothepoint: DEBUG
---

spring:
  profiles: docker
  data:
    mongodb:
      host: bediende-mongo
  rabbitmq:
      host: rabbitmq
app:
  rabbitmq:
      host: rabbitmq
server:
  port: 8080